# Generated by Django 3.2.6 on 2021-09-29 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=150)),
                ('referencia', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=150)),
                ('pais', models.IntegerField(choices=[('0', 'GUATEMALA')])),
                ('region', models.IntegerField(choices=[('0', 'Alta Verapaz'), ('1', 'Baja Verapaz'), ('2', 'Chimaltenago'), ('3', 'Chiquimula'), ('4', 'Guatemala'), ('5', 'El Progreso'), ('6', 'Escuintla'), ('7', 'Huehuetenango'), ('8', 'Izabal'), ('9', 'Jalapa'), ('10', 'Jutiapa'), ('11', 'Petén'), ('12', 'Quetzaltenango'), ('13', 'Quiché'), ('14', 'Retalhuleu'), ('15', 'Sacatepequez'), ('16', 'San Marcos'), ('17', 'Santa Rosa'), ('18', 'Sololá'), ('19', 'Suchitepequez'), ('20', 'Totonicapán'), ('21', 'Zacapa')])),
                ('zipcode', models.CharField(max_length=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='producto_imagen')),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_p', to='tienda.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('fecha_orden', models.DateTimeField(blank=True, null=True)),
                ('status_orden', models.BooleanField(default=False)),
                ('direccion_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion_envio', to='tienda.direccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
