# Generated by Django 3.2.6 on 2021-09-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_s',
        ),
    ]
